### ISSUE TITLE
docker-compose scale

### ISSUE THREAD

**Issue by stela5** [CenturyLinkLabs/zodiac#27]
Great work on Zodiac!  Feature request: support `docker-compose scale` functionality (and superhero points for automatic load balancing)

**Comment by alexwelch** [comment]
Thanks for the feedback @stela5 - `scale` is definitely on our roadmap. We'll leave this open in the meantime, and let you know when support for scale exists. If you're a programmer yourself we also welcome contributions. 

Thanks

**Comment by alexwelch** [comment]
@stela5 - One thing that may already be obvious, but I wanted to mention anyway, is that you can just use docker-compose scale for now (with docker-compose pointed at the remote DOCKER_HOST), you just won't get the versioning like you do when you deploy. 

With a Zodiac scale we were planning on having that create another entry in the deployment history, so that you could rollback a scale operation, etc.

Is that in line with what you were thinking?

**Comment by stela5** [comment]
Right, I just wanted a Zodiac shorthand for the same functionality with the additional logging sugar.
